spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.61.130:3307/springinaction
    username: root
    password: root
  sql:
    init:
      mode: never

logging:
  level:
    org:
      springframework:
        security: debug
    root: info