server:
  port: 8080
spring:
  data:
    rest:
      base-path: /api # 设置spring data生成的rest API的请求前缀
  rabbitmq:
    host: 192.168.61.130
    port: 5672
    username: itaiit-rabbitmq
    password: admin
    template:
      exchange: tacocloud.orders
      routing-key: kitchens.central
  profiles:
    active: webflux

logging:
  level:
    org:
      springframework:
        security: debug
        data: debug
    root: info

taco:
  page: 0
  size: 4

---
spring:
  config:
    activate:
      on-profile: webservlet
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.61.130:3307/springinaction
    username: root
    password: root
  sql:
    init:
      mode: never
  jpa:
    database: mysql
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---
spring:
  config:
    activate:
      on-profile: webflux
  main:
    allow-bean-definition-overriding: true
  data:
    cassandra:
      local-datacenter: datacenter1
      keyspace-name: tacocloud
      contact-points:
        - 192.168.61.130:9042
      schema-action: create_if_not_exists