server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.61.130:3307/springinaction
    username: root
    password: root
  sql:
    init:
      mode: never
  data:
    rest:
      base-path: /api # 设置spring data生成的rest API的请求前缀
  jpa:
    database: mysql
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    org:
      springframework:
        security: debug
    root: info